[project]
name = "adafede-github-io"
version = "0.0.1"
description = "My personal website"
requires-python = "==3.13.*"
dependencies = [
  "bs4>=0.0.2",
  "circlify>=0.15.1",
  "cmcrameri>=1.10",
  "commonmeta-py>=0.272",
  "folium>=0.20.0",
  "geopy>=2.5.0",
  "ipython>=9.16.1",
  "lxml>=6.1.2",
  "markdown>=3.10.3",
  "matplotlib>=3.11.1",
  "pyyaml>=6.0.3",
  "quarto>=0.1.0",
  "ruamel-yaml>=0.19.1",
]

[dependency-groups]
dev = [
  "prek>=0.4.14",
  "pytest>=9.1.1",
]

[tool.deptry]
known_first_party = [
  "config",
  "infrastructure",
  "scripts",
  "services",
  "utilities",
]

[tool.deptry.package_module_name_map]
commonmeta-py = [
  "commonmeta",
]
ipython = [
  "IPython",
]
pyyaml = [
  "yaml",
]
PyYAML = [
  "yaml",
]
ruamel-yaml = [
  "ruamel",
  "ruamel.yaml",
]

[tool.deptry.per_rule_ignores]
DEP002 = ["quarto", "circlify", "cmcrameri"]

[tool.pyright]
reportUnknownImportedSymbol = "warning"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]

[tool.ty.rules]
unresolved-import = "ignore"
