---
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published
  workflow_dispatch: null
name: Publish
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: read
  discussions: read
  packages: write
  pages: write
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  publish:
    runs-on: codeberg-small
    container:
      image: ghcr.io/mcanouil/quarto-codespaces:latest
    concurrency:
      group: altdoc-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential nasm libqpdf-dev libxslt1-dev \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
          # Update tlmgr and install packages via TeX Live manager
          sudo tlmgr update --self
          sudo tlmgr install xifthen koma-script ifthen
      - name: Install required R packages
        run: |
          Rscript -e "install.packages('pak', repos = 'https://r-lib.github.io/p/pak/stable/')"
          Rscript -e "pak::pkg_install(c('rmarkdown', 'knitr'))"
      - name: Build site
        run: |
          uv run quarto render
      - uses: actions/git-pages@v2
        with:
          site: https://adafede.codeberg.page/
          token: ${{ forge.token }}
          source: _site/