"""
Pandoc PDF generator for QMD posts.

Converts markdown files to PDF using Pandoc with bibliography processing
and CiTO filters. Uses the refactored infrastructure layer.
"""

import subprocess
import sys
from pathlib import Path
from typing import List

# Add parent directory to path for infrastructure imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from infrastructure import FileSystem, get_logger

logger = get_logger(__name__)


# ============================================================================
# CONSTANTS
# ============================================================================

POSTS_DIR = Path("posts")
SITE_POSTS_DIR = Path("_site/posts")
BIBLIOGRAPHY_FILE = Path("posts/references.bib")
CSL_FILE = Path("journal-of-cheminformatics.csl")

PANDOC_FILTERS = [
    Path("filters/extract-cito.lua"),
    Path("filters/insert-cito-in-ref.lua"),
]


# ============================================================================
# PANDOC PROCESSING
# ============================================================================


def build_pandoc_command(md_path: Path, pdf_path: Path) -> List[str]:
    """Build Pandoc command for PDF generation.

    Args:
        md_path: Path to markdown file
        pdf_path: Path for output PDF file

    Returns:
        List of command arguments
    """
    cmd = [
        "pandoc",
        str(md_path),
        "--to=pdf",
        f"--bibliography={BIBLIOGRAPHY_FILE}",
        f"--lua-filter={PANDOC_FILTERS[0]}",
        "--citeproc",
        f"--lua-filter={PANDOC_FILTERS[1]}",
        f"--csl={CSL_FILE}",
        "-o",
        str(pdf_path),
    ]
    return cmd


def convert_md_to_pdf(md_path: Path, pdf_path: Path) -> bool:
    """Convert markdown file to PDF using Pandoc.

    Args:
        md_path: Path to markdown file
        pdf_path: Path for output PDF file

    Returns:
        True if successful, False otherwise
    """
    cmd = build_pandoc_command(md_path, pdf_path)

    logger.debug(f"Running: {' '.join(cmd)}")

    try:
        result = subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            text=True,
        )
        logger.info(f"✓ Generated PDF: {pdf_path.name}")
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"✗ Pandoc failed for {md_path.name}: {e.stderr}")
        return False
    except FileNotFoundError:
        logger.error("Pandoc not found. Please install Pandoc.")
        return False


def run_pandoc_for_all_qmds() -> None:
    """Convert all QMD posts to PDF using Pandoc.

    Processes all QMD files in the posts directory, converting their
    corresponding markdown files (generated by Quarto) to PDF.
    Uses FileSystem service for file operations.
    """
    # Initialize FileSystem
    project_root = Path.cwd()
    fs = FileSystem(project_root)

    # Find all QMD files
    qmd_files = fs.find_posts("posts")

    if not qmd_files:
        logger.warning(f"No QMD files found in {POSTS_DIR}")
        return

    logger.info(f"Converting {len(qmd_files)} posts to PDF")

    # Check if bibliography exists
    if not fs.exists(BIBLIOGRAPHY_FILE):
        logger.warning(f"Bibliography not found: {BIBLIOGRAPHY_FILE}")

    # Check if CSL file exists
    if not fs.exists(CSL_FILE):
        logger.warning(f"CSL file not found: {CSL_FILE}")

    success_count = 0
    skip_count = 0
    fail_count = 0

    for qmd_file in qmd_files:
        base_name = qmd_file.stem
        md_path = SITE_POSTS_DIR / f"{base_name}.md"
        pdf_path = SITE_POSTS_DIR / f"{base_name}.pdf"

        # Check if markdown file exists
        if not fs.exists(md_path):
            logger.debug(f"Skipping {qmd_file.name}: markdown not found at {md_path}")
            skip_count += 1
            continue

        # Convert to PDF
        if convert_md_to_pdf(md_path, pdf_path):
            success_count += 1
        else:
            fail_count += 1

    # Summary
    logger.info("=" * 60)
    logger.info("PDF Generation Summary:")
    logger.info(f"  Success: {success_count}")
    logger.info(f"  Skipped: {skip_count} (markdown not found)")
    logger.info(f"  Failed:  {fail_count}")
    logger.info("=" * 60)


if __name__ == "__main__":
    run_pandoc_for_all_qmds()
