---
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published
  workflow_dispatch: null
name: Publish
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: read
  discussions: read
  packages: write
  pages: write
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: altdoc-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc nasm libqpdf-dev libxml2-dev libxslt1-dev make
      - uses: astral-sh/setup-uv@v7
      - uses: pandoc/actions/setup@v1
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - name: Build site
        run: |
          uv run quarto render
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
